# Generated by Django 5.1.7 on 2025-05-30 07:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkSchedule',
            fields=[
                ('employee_title', models.CharField(blank=True, max_length=100, null=True)),
                ('official_start', models.TimeField(blank=True, null=True)),
                ('official_end', models.TimeField(blank=True, null=True)),
                ('relief_start', models.TimeField(blank=True, null=True)),
                ('relief_end', models.TimeField(blank=True, null=True)),
                ('late_in_start', models.TimeField(blank=True, null=True)),
                ('late_in_end', models.TimeField(blank=True, null=True)),
                ('covering_start', models.TimeField(blank=True, null=True)),
                ('covering_end', models.TimeField(blank=True, null=True)),
                ('short_leave_morning_start', models.TimeField(blank=True, null=True)),
                ('short_leave_morning_end', models.TimeField(blank=True, null=True)),
                ('short_leave_evening_start', models.TimeField(blank=True, null=True)),
                ('short_leave_evening_end', models.TimeField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Work Schedule',
                'verbose_name_plural': 'Employee Work Schedules',
            },
        ),
    ]
