# Generated by Django 5.1.7 on 2025-06-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkschedule',
            name='employee_title_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
