# Generated by Django 5.1.7 on 2025-06-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0002_employeeworkschedule_employee_title_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkschedule',
            name='half_leave_evening_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkschedule',
            name='half_leave_evening_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkschedule',
            name='half_leave_morning_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkschedule',
            name='half_leave_morning_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
