# Generated by Django 5.1.7 on 2025-06-17 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0003_employeeworkschedule_half_leave_evening_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('leave_type', models.CharField(blank=True, max_length=50, null=True)),
                ('balance', models.CharField(blank=True, choices=[('short', 'Short Leave'), ('half', 'Half Day Leave')], max_length=50, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
            },
        ),
    ]
