# Generated by Django 5.1.7 on 2025-06-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0004_leavebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
