# Generated by Django 5.1.7 on 2025-06-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0005_leavebalance_month_leavebalance_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='balance',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='half_leave_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='late_count',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='late_count_covered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='short_leave_balance',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('short', 'Short Leave'), ('half', 'Half Day Leave')], max_length=50, null=True),
        ),
    ]
