# Generated by Django 5.1.7 on 2025-06-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management', '0006_remove_leavebalance_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='is_late_covered_totally',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
