# Generated by Django 5.1.7 on 2025-04-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
