# Generated by Django 5.1.7 on 2025-04-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['employee_id', 'date']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee_id',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
