# Generated by Django 5.1.7 on 2025-06-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management', '0003_alter_attendance_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_half_day_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_short_leave',
            field=models.BooleanField(default=False),
        ),
    ]
